### ISSUE TITLE
Stop using deprecated Google Cloud APIs that are shutting down

### ISSUE THREAD

**Issue by balloob** [home-assistant/mobile-apps-fcm-push#1]
**From Google:**

Our records show that you own projects with App Engine applications or Cloud Functions that are still calling the pre-GA v0.1 and v1beta1 endpoints of the App Engine and Cloud Functions metadata server.

We’re writing to remind you that these legacy endpoints are scheduled to be turned down on April 30, 2020. After April 30, 2020, requests to the v0.1 and v1beta1 endpoints will no longer be supported, and may return HTTP 404 NOT FOUND responses. As a result, before April 30, 2020, you will need to update your requests to use the v1 endpoint, which was available starting in 2016.

You are likely accessing the metadata server in one of two ways:

   1. Using an old Google client library which is making requests to the legacy endpoints
   2. Making a direct request in your code

**Action:**

We should update our Google client libs

**Comment by robbiet480** [comment]
Fixed by #2
