### ISSUE TITLE
ERROR (MainThread) [homeassistant.components.mobile_app.notify] SenderId mismatch. This message is generated externally to Home Assistant.

### ISSUE THREAD

**Issue by lucaardito** [home-assistant/mobile-apps-fcm-push#104]
I am building the Android and iOS apps from the source code. Everything works fine but the iOS push notifications. I set up certificates on the apple developer portal, and then uploaded them on the firebase console. I downloaded the plist and everything compiles correctly. When I try sending a notification from Home Assistant I get this error 

ERROR (MainThread) [homeassistant.components.mobile_app.notify] SenderId mismatch. This message is generated externally to Home Assistant.

what am I missing?

EDIT

I found a solution myself. These two links
```
rg https://mobile-apps.home-assistant.io/
App/Settings/Notifications/NotificationRateLimitsAPI.swift
27:                    string: "https://mobile-apps.home-assistant.io/api/checkRateLimits"

Shared/API/HAAPI.swift
449:                    "push_url": "https://mobile-apps.home-assistant.io/api/sendPushNotification",

```

 need to be changed with the ones provided on the Firebase console.
 
May I ask why these important URLs are not placed as parameters in some config files? Could you please point me to some documentation where this is explained?

**Comment by robbiet480** [comment]
You're welcome to submit a PR into the iOS and Android repos to make the URLs set by a config file.

**Comment by heisenberg2980** [comment]
@lucaardito did you have the same issue with the android app?
