### ISSUE TITLE
Not able to run the build

### ISSUE THREAD

**Issue by ApexInfosysIndia** [home-assistant/mobile-apps-fcm-push#11]
root@hass:/home/mobile-apps-fcm-push/functions# firebase functions:config:set debug.local=true

Error: Authorization failed. This account is missing the following required permissions on project home-assistant-mobile-apps:

  firebase.projects.get
  runtimeconfig.configs.create
  runtimeconfig.configs.delete
  runtimeconfig.configs.get
  runtimeconfig.configs.list
  runtimeconfig.configs.update
  runtimeconfig.variables.create
  runtimeconfig.variables.delete
  runtimeconfig.variables.get
  runtimeconfig.variables.list
  runtimeconfig.variables.update

root@hass:/home/mobile-apps-fcm-push/functions# firebase functions:config:get > .runtimeconfig.json

Error: Authorization failed. This account is missing the following required permissions on project home-assistant-mobile-apps:

  firebase.projects.get
  runtimeconfig.configs.get
  runtimeconfig.configs.list
  runtimeconfig.variables.get
  runtimeconfig.variables.list

**Comment by robbiet480** [comment]
You'll need to configure your own Firebase project and change the project ID found in `.firebaserc`.
