### ISSUE TITLE
How to use with VPN ?

### ISSUE THREAD

**Issue by JohannCR** [home-assistant/mobile-apps-fcm-push#74]
When using a VPN no notifications are sent while it works normally when vpn is deactivated.
Is it a bug with fcm push or an incomplete setup ?
Thanks for any help

**Comment by arallsopp** [comment]
> When using a VPN no notifications are sent [...] Is it a bug with fcm push [...]

I use the official mobile app notifications with tailscale VPN on iOS and it works without issue, if that helps?
